apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
    name: jaeger
    namespace: istio-system
    labels:
        app: jaeger
spec:
    hosts:
    - {{ .Values.jaeger }}
    gateways:
    - jaeger
    http:
        - route:
            - destination:
                host: jaeger-query
                port:
                    number: 16686