apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
    name: kiali
    namespace: istio-system
    labels:
        app: kiali
spec:
    hosts:
    - {{ .Values.kiali }}
    gateways:
    - kiali
    http:
        - route:
            - destination:
                host: kiali
                port:
                    number: 20001