apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
    name: prometheus
    namespace: istio-system
    labels:
        app: prometheus
spec:
    hosts:
    - {{ .Values.prometheus }}
    gateways:
    - prometheus
    http:
        - route:
            - destination:
                host: prometheus
                port:
                    number: 9090