apiVersion: v1
kind: Service
metadata:
  name: emailservice
  namespace: {{ .Values.namespace }}
  labels:
    app: emailservice
    release: {{ .Release.Name }}
spec:
  type: ClusterIP
  selector:
    app: emailservice
    release: {{ .Release.Name }}
  ports:
  - name: grpc
    port: 5000
    targetPort: 8080

