apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: {{ .Values.namespace }}
  labels:
    app: frontend
    release: {{ .Release.Name }}
spec:
  type: ClusterIP
  selector:
    app: frontend
   # release: {{ .Release.Name }}
  ports:
  - name: http
    port: 80
    targetPort: 8080