apiVersion: v1
kind: Service
metadata:
  name: currencyservice
  namespace: {{ .Values.namespace }}
  labels:
    app: currencyservice
    release: {{ .Release.Name }}
spec:
  type: ClusterIP
  selector:
    app: currencyservice
    release: {{ .Release.Name }}
  ports:
  - name: grpc
    port: 7000
    targetPort: 7000


