apiVersion: v1
kind: Service
metadata:
  name: paymentservice
  namespace: {{ .Values.namespace }}
  labels:
    app: paymentservice
    release: {{ .Release.Name }}
spec:
  type: ClusterIP
  selector:
    app: paymentservice
    release: {{ .Release.Name }}
  ports:
  - name: grpc
    port: 50051
    targetPort: 50051
