apiVersion: v1
kind: Service
metadata:
  name: cartservice
  namespace: {{ .Values.namespace }}
  labels:
    app: cartservice
    release: {{ .Release.Name }}
spec:
  type: ClusterIP
  selector:
    app: cartservice
    release: {{ .Release.Name }}
  ports:
  - name: grpc
    port: 7070
    targetPort: 7070
