apiVersion: v1
kind: Service
metadata:
  name: checkoutservice
  namespace: {{ .Values.namespace }}
  labels:
    app: checkoutservice
    release: {{ .Release.Name }}
spec:
  type: ClusterIP
  selector:
    app: checkoutservice
    release: {{ .Release.Name }}
  ports:
  - name: grpc
    port: 5050
    targetPort: 5050

