apiVersion: v1
kind: Service
metadata:
  name: productcatalogservice
  namespace: {{ .Values.namespace }}
  labels:
    app: productcatalogservice
    release: {{ .Release.Name }}
spec:
  type: ClusterIP
  selector:
    app: productcatalogservice
    release: {{ .Release.Name }}
  ports:
  - name: grpc
    port: 3550
    targetPort: 3550
